In [4]:
import pandas as pd
import numpy as np

In [5]:
data = pd.read_csv("NYC_Jobs.csv")
data.head()

,Job ID,Civil Service Title,Agency,Posting Type,Job Category,Salary Range From,Salary Range To
0,424339,PUBLIC HEALTH NURSE,DEPT OF HEALTH/MENTAL HYGIENE,External,Health,84252.0,84252.0
1,379094,CERT IT DEVELOPER (APP),NYC EMPLOYEES RETIREMENT SYS,External,NaN,82884.0,116391.0
2,520417,EXECUTIVE AGENCY COUNSEL,NYC HOUSING AUTHORITY,External,Legal Affairs,105000.0,125000.0
3,233549,CERTIFIED IT ADMINISTRATOR (LA,NYC EMPLOYEES RETIREMENT SYS,External,Information Technology & Telecommunications,87203.0,131623.0
4,510256,ASSOCIATE HUMAN RIGHTS SPECIAL,HUMAN RIGHTS COMMISSION,External,Constituent Services & Community Programs,58449.0,67216.0

In [6]:
data.fillna('kitten')

,Job ID,Civil Service Title,Agency,Posting Type,Job Category,Salary Range From,Salary Range To
0,424339,PUBLIC HEALTH NURSE,DEPT OF HEALTH/MENTAL HYGIENE,External,Health,84252.0,84252.0
1,379094,CERT IT DEVELOPER (APP),NYC EMPLOYEES RETIREMENT SYS,External,kitten,82884.0,116391.0
2,520417,EXECUTIVE AGENCY COUNSEL,NYC HOUSING AUTHORITY,External,Legal Affairs,105000.0,125000.0
3,233549,CERTIFIED IT ADMINISTRATOR (LA,NYC EMPLOYEES RETIREMENT SYS,External,Information Technology & Telecommunications,87203.0,131623.0
4,510256,ASSOCIATE HUMAN RIGHTS SPECIAL,HUMAN RIGHTS COMMISSION,External,Constituent Services & Community Programs,58449.0,67216.0
...,...,...,...,...,...,...,...
3768,457839,CERTIFIED IT ADMINISTRATOR (LA,NYC EMPLOYEES RETIREMENT SYS,Internal,"Technology, Data & Innovation",85371.0,119883.0
3769,527141,ASSOCIATE HOUSING DEVELOPMENT,HOUSING PRESERVATION & DVLPMNT,Internal,"Engineering, Architecture, & Planning",74650.0,85847.0
3770,509443,SENIOR IT ARCHITECT,FINANCIAL INFO SVCS AGENCY,Internal,"Technology, Data & Innovation",100000.0,115000.0
3771,352367,ECONOMIST,DEPT OF HEALTH/MENTAL HYGIENE,Internal,"Finance, Accounting, & Procurement",42288.0,59400.0
3772,478739,AGENCY ATTORNEY INTERNE,HUMAN RIGHTS COMMISSION,External,Legal Affairs,62397.0,71757.0

In [7]:
data.replace("NYC HOUSING AUTHORITY","NYC AUTHORITY FOR HOUSING")
data.replace("NYC HOUSING AUTHORITY",'NYC_Hous_A', inplace=True)

,Job ID,Civil Service Title,Agency,Posting Type,Job Category,Salary Range From,Salary Range To
0,424339,PUBLIC HEALTH NURSE,DEPT OF HEALTH/MENTAL HYGIENE,External,Health,84252.0,84252.0
1,379094,CERT IT DEVELOPER (APP),NYC EMPLOYEES RETIREMENT SYS,External,NaN,82884.0,116391.0
2,520417,EXECUTIVE AGENCY COUNSEL,NYC AUTHORITY FOR HOUSING,External,Legal Affairs,105000.0,125000.0
3,233549,CERTIFIED IT ADMINISTRATOR (LA,NYC EMPLOYEES RETIREMENT SYS,External,Information Technology & Telecommunications,87203.0,131623.0
4,510256,ASSOCIATE HUMAN RIGHTS SPECIAL,HUMAN RIGHTS COMMISSION,External,Constituent Services & Community Programs,58449.0,67216.0
...,...,...,...,...,...,...,...
3768,457839,CERTIFIED IT ADMINISTRATOR (LA,NYC EMPLOYEES RETIREMENT SYS,Internal,"Technology, Data & Innovation",85371.0,119883.0
3769,527141,ASSOCIATE HOUSING DEVELOPMENT,HOUSING PRESERVATION & DVLPMNT,Internal,"Engineering, Architecture, & Planning",74650.0,85847.0
3770,509443,SENIOR IT ARCHITECT,FINANCIAL INFO SVCS AGENCY,Internal,"Technology, Data & Innovation",100000.0,115000.0
3771,352367,ECONOMIST,DEPT OF HEALTH/MENTAL HYGIENE,Internal,"Finance, Accounting, & Procurement",42288.0,59400.0
3772,478739,AGENCY ATTORNEY INTERNE,HUMAN RIGHTS COMMISSION,External,Legal Affairs,62397.0,71757.0

In [8]:
# Changes the value in the original dataframe

data.loc[data["Posting Type"] == "External", "Posting Type"] = 1
data.at[data["Posting Type"] == 1,'Civil Service Title']='CITA'
data.loc[0, "Posting Type"] = "Unknown" #works with at too

In [14]:
data.loc[0, "Posting Type"] = 12

In [15]:
data

,Job ID,Civil Service Title,Agency,Posting Type,Job Category,Salary Range From,Salary Range To
0,424339,CITA,DEPT OF HEALTH/MENTAL HYGIENE,12,Health,84252.0,84252.0
1,379094,CITA,NYC EMPLOYEES RETIREMENT SYS,1,NaN,82884.0,116391.0
2,520417,CITA,NYC HOUSING AUTHORITY,1,Legal Affairs,105000.0,125000.0
3,233549,CITA,NYC EMPLOYEES RETIREMENT SYS,1,Information Technology & Telecommunications,87203.0,131623.0
4,510256,CITA,HUMAN RIGHTS COMMISSION,1,Constituent Services & Community Programs,58449.0,67216.0
...,...,...,...,...,...,...,...
3768,457839,CERTIFIED IT ADMINISTRATOR (LA,NYC EMPLOYEES RETIREMENT SYS,Internal,"Technology, Data & Innovation",85371.0,119883.0
3769,527141,ASSOCIATE HOUSING DEVELOPMENT,HOUSING PRESERVATION & DVLPMNT,Internal,"Engineering, Architecture, & Planning",74650.0,85847.0
3770,509443,SENIOR IT ARCHITECT,FINANCIAL INFO SVCS AGENCY,Internal,"Technology, Data & Innovation",100000.0,115000.0
3771,352367,ECONOMIST,DEPT OF HEALTH/MENTAL HYGIENE,Internal,"Finance, Accounting, & Procurement",42288.0,59400.0
3772,478739,CITA,HUMAN RIGHTS COMMISSION,1,Legal Affairs,62397.0,71757.0

In [19]:
data["is_LegalAffairs"] = np.where(data["Job Category"] == "Legal Affairs", 1, 0)

In [20]:
data

,Job ID,Civil Service Title,Agency,Posting Type,Job Category,Salary Range From,Salary Range To,is_LegalAffairs
0,424339,CITA,DEPT OF HEALTH/MENTAL HYGIENE,12,Health,84252.0,84252.0,0
1,379094,CITA,NYC EMPLOYEES RETIREMENT SYS,1,NaN,82884.0,116391.0,0
2,520417,CITA,NYC HOUSING AUTHORITY,1,Legal Affairs,105000.0,125000.0,1
3,233549,CITA,NYC EMPLOYEES RETIREMENT SYS,1,Information Technology & Telecommunications,87203.0,131623.0,0
4,510256,CITA,HUMAN RIGHTS COMMISSION,1,Constituent Services & Community Programs,58449.0,67216.0,0
...,...,...,...,...,...,...,...,...
3768,457839,CERTIFIED IT ADMINISTRATOR (LA,NYC EMPLOYEES RETIREMENT SYS,Internal,"Technology, Data & Innovation",85371.0,119883.0,0
3769,527141,ASSOCIATE HOUSING DEVELOPMENT,HOUSING PRESERVATION & DVLPMNT,Internal,"Engineering, Architecture, & Planning",74650.0,85847.0,0
3770,509443,SENIOR IT ARCHITECT,FINANCIAL INFO SVCS AGENCY,Internal,"Technology, Data & Innovation",100000.0,115000.0,0
3771,352367,ECONOMIST,DEPT OF HEALTH/MENTAL HYGIENE,Internal,"Finance, Accounting, & Procurement",42288.0,59400.0,0
3772,478739,CITA,HUMAN RIGHTS COMMISSION,1,Legal Affairs,62397.0,71757.0,1

In [22]:
data['Civil Service Title'].mask(data['Civil Service Title'] == 'SENIOR IT ARCHITECT', 0, inplace=False)

0                                 CITA
1                                 CITA
2                                 CITA
3                                 CITA
4                                 CITA
                     ...
3768    CERTIFIED IT ADMINISTRATOR (LA
3769     ASSOCIATE HOUSING DEVELOPMENT
3770                                 0
3771                         ECONOMIST
3772                              CITA
Name: Civil Service Title, Length: 3773, dtype: object

In [23]:
data

,Job ID,Civil Service Title,Agency,Posting Type,Job Category,Salary Range From,Salary Range To,is_LegalAffairs
0,424339,CITA,DEPT OF HEALTH/MENTAL HYGIENE,12,Health,84252.0,84252.0,0
1,379094,CITA,NYC EMPLOYEES RETIREMENT SYS,1,NaN,82884.0,116391.0,0
2,520417,CITA,NYC HOUSING AUTHORITY,1,Legal Affairs,105000.0,125000.0,1
3,233549,CITA,NYC EMPLOYEES RETIREMENT SYS,1,Information Technology & Telecommunications,87203.0,131623.0,0
4,510256,CITA,HUMAN RIGHTS COMMISSION,1,Constituent Services & Community Programs,58449.0,67216.0,0
...,...,...,...,...,...,...,...,...
3768,457839,CERTIFIED IT ADMINISTRATOR (LA,NYC EMPLOYEES RETIREMENT SYS,Internal,"Technology, Data & Innovation",85371.0,119883.0,0
3769,527141,ASSOCIATE HOUSING DEVELOPMENT,HOUSING PRESERVATION & DVLPMNT,Internal,"Engineering, Architecture, & Planning",74650.0,85847.0,0
3770,509443,SENIOR IT ARCHITECT,FINANCIAL INFO SVCS AGENCY,Internal,"Technology, Data & Innovation",100000.0,115000.0,0
3771,352367,ECONOMIST,DEPT OF HEALTH/MENTAL HYGIENE,Internal,"Finance, Accounting, & Procurement",42288.0,59400.0,0
3772,478739,CITA,HUMAN RIGHTS COMMISSION,1,Legal Affairs,62397.0,71757.0,1

In [39]:
def capitalize(text):
    return text.lower().capitalize()

data['Civil Service Title'].apply(capitalize)

0                  Public health nurse
1              Cert it developer (app)
2             Executive agency counsel
3       Certified it administrator (la
4       Associate human rights special
                     ...
3768    Certified it administrator (la
3769     Associate housing development
3770               Senior it architect
3771                         Economist
3772           Agency attorney interne
Name: Civil Service Title, Length: 3773, dtype: object

In [43]:
def replace_values(text):
    if text == 'NYC EMPLOYEES RETIREMENT SYS':
        return 'Retirement SYS'
    elif text == 'HUMAN RIGHTS COMMISSION':
        return 'HRC'
    else:
        return text

data['Agency'] = data['Agency'].apply(replace_values)

In [44]:
data

,Job ID,Civil Service Title,Agency,Posting Type,Job Category,Salary Range From,Salary Range To
0,424339,Public health nurse,DEPT OF HEALTH/MENTAL HYGIENE,External,Health,84252.0,84252.0
1,379094,Cert it developer (app),Retirement SYS,External,NaN,82884.0,116391.0
2,520417,Executive agency counsel,NYC HOUSING AUTHORITY,External,Legal Affairs,105000.0,125000.0
3,233549,Certified it administrator (la,Retirement SYS,External,Information Technology & Telecommunications,87203.0,131623.0
4,510256,Associate human rights special,HRC,External,Constituent Services & Community Programs,58449.0,67216.0
...,...,...,...,...,...,...,...
3768,457839,Certified it administrator (la,Retirement SYS,Internal,"Technology, Data & Innovation",85371.0,119883.0
3769,527141,Associate housing development,HOUSING PRESERVATION & DVLPMNT,Internal,"Engineering, Architecture, & Planning",74650.0,85847.0
3770,509443,Senior it architect,FINANCIAL INFO SVCS AGENCY,Internal,"Technology, Data & Innovation",100000.0,115000.0
3771,352367,Economist,DEPT OF HEALTH/MENTAL HYGIENE,Internal,"Finance, Accounting, & Procurement",42288.0,59400.0
3772,478739,Agency attorney interne,HRC,External,Legal Affairs,62397.0,71757.0

In [26]:
data['Agency'].map({'NYC HOUSING AUTHORITY':'NYC_H_A'})

AttributeError: 'DataFrame' object has no attribute 'map'

In [29]:
def add_year(value):
    return str(value) + '_2022'
    

data[['Job ID', 'Civil Service Title']] = data[['Job ID', 'Civil Service Title']].applymap(add_year)

In [30]:
data

,Job ID,Civil Service Title,Agency,Posting Type,Job Category,Salary Range From,Salary Range To,is_LegalAffairs
0,424339_2022,CITA_2022,DEPT OF HEALTH/MENTAL HYGIENE,12,Health,84252.0,84252.0,0
1,379094_2022,CITA_2022,NYC EMPLOYEES RETIREMENT SYS,1,NaN,82884.0,116391.0,0
2,520417_2022,CITA_2022,NYC HOUSING AUTHORITY,1,Legal Affairs,105000.0,125000.0,1
3,233549_2022,CITA_2022,NYC EMPLOYEES RETIREMENT SYS,1,Information Technology & Telecommunications,87203.0,131623.0,0
4,510256_2022,CITA_2022,HUMAN RIGHTS COMMISSION,1,Constituent Services & Community Programs,58449.0,67216.0,0
...,...,...,...,...,...,...,...,...
3768,457839_2022,CERTIFIED IT ADMINISTRATOR (LA_2022,NYC EMPLOYEES RETIREMENT SYS,Internal,"Technology, Data & Innovation",85371.0,119883.0,0
3769,527141_2022,ASSOCIATE HOUSING DEVELOPMENT_2022,HOUSING PRESERVATION & DVLPMNT,Internal,"Engineering, Architecture, & Planning",74650.0,85847.0,0
3770,509443_2022,SENIOR IT ARCHITECT_2022,FINANCIAL INFO SVCS AGENCY,Internal,"Technology, Data & Innovation",100000.0,115000.0,0
3771,352367_2022,ECONOMIST_2022,DEPT OF HEALTH/MENTAL HYGIENE,Internal,"Finance, Accounting, & Procurement",42288.0,59400.0,0
3772,478739_2022,CITA_2022,HUMAN RIGHTS COMMISSION,1,Legal Affairs,62397.0,71757.0,1

In [34]:
data['Salary range'] = pd.cut(data['Salary Range From'], 3)
data

,Job ID,Civil Service Title,Agency,Posting Type,Job Category,Salary Range From,Salary Range To,is_LegalAffairs,Salary range
0,424339_2022,CITA_2022,DEPT OF HEALTH/MENTAL HYGIENE,12,Health,84252.0,84252.0,0,"(83333.333, 166666.667]"
1,379094_2022,CITA_2022,NYC EMPLOYEES RETIREMENT SYS,1,NaN,82884.0,116391.0,0,"(-250.0, 83333.333]"
2,520417_2022,CITA_2022,NYC HOUSING AUTHORITY,1,Legal Affairs,105000.0,125000.0,1,"(83333.333, 166666.667]"
3,233549_2022,CITA_2022,NYC EMPLOYEES RETIREMENT SYS,1,Information Technology & Telecommunications,87203.0,131623.0,0,"(83333.333, 166666.667]"
4,510256_2022,CITA_2022,HUMAN RIGHTS COMMISSION,1,Constituent Services & Community Programs,58449.0,67216.0,0,"(-250.0, 83333.333]"
...,...,...,...,...,...,...,...,...,...
3768,457839_2022,CERTIFIED IT ADMINISTRATOR (LA_2022,NYC EMPLOYEES RETIREMENT SYS,Internal,"Technology, Data & Innovation",85371.0,119883.0,0,"(83333.333, 166666.667]"
3769,527141_2022,ASSOCIATE HOUSING DEVELOPMENT_2022,HOUSING PRESERVATION & DVLPMNT,Internal,"Engineering, Architecture, & Planning",74650.0,85847.0,0,"(-250.0, 83333.333]"
3770,509443_2022,SENIOR IT ARCHITECT_2022,FINANCIAL INFO SVCS AGENCY,Internal,"Technology, Data & Innovation",100000.0,115000.0,0,"(83333.333, 166666.667]"
3771,352367_2022,ECONOMIST_2022,DEPT OF HEALTH/MENTAL HYGIENE,Internal,"Finance, Accounting, & Procurement",42288.0,59400.0,0,"(-250.0, 83333.333]"
3772,478739_2022,CITA_2022,HUMAN RIGHTS COMMISSION,1,Legal Affairs,62397.0,71757.0,1,"(-250.0, 83333.333]"

In [61]:
df = pd.DataFrame({'A': [1, 2, 3],
                   'B': [400, 500, 600]})
new_df = pd.DataFrame({'B': [4, 5, 6],
                       'C': [7, 8, 9]})

In [62]:
df

   A    B
0  1  400
1  2  500
2  3  600

In [63]:
new_df

   B  C
0  4  7
1  5  8
2  6  9

In [66]:
df.update(new_df)
df

   A  B
0  1  4
1  2  5
2  3  6